### ISSUE TITLE
Setup medalRound logic

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#29]
Setup logic for medalRound U12-U19 teams

**Comment by ahundiak** [comment]
ScheduleMedalRoundCalculator:: generateQuarterFinals
- Why the 'current' in $poolGames = current($pool['games']); ?
- You have the method comments switched around
- Doing a fair amount of string manipulations for keys, hope to simplify this for ng2016

ScheduleMedalRoundCalculator:: generateSemiFinals
- Missing the logic for runner ups?
- Be nice to come up with a politically correct three letter acronym for the loser of a game

Not really fond of the generateScheduleResults.  Mixing business logic with presentation.  But okay for now.  Same for the getTeamList and connection object.

I would like to see the tests refactored to use test data instead of pulling info from the connection.  Consider making a yaml file with same games and loading it in.  Then actually check the results with asserts.  That way we can ensure we are getting the correct results for the edge cases.  

Maybe update the Points and Standings calculator as well.

Directory refactoring

Move the three calculators to Results\Calculator.  We can get rid of the AbstractResults and the NatGamesResults.  I had copied them for reference.

Move the MedalRound controller and view to Schedule\MedalRound.  

I would suggest merging/rebasing in the master branch to keep from getting too far out of sync.

**Comment by ahundiak** [comment]
Actually there is one big logic issue in the quarter finals that needs to be addresses.  This is where having fixed test cases will be needed. 

Need to handle the case where we have three pools.  There will always be 8 teams advancing, the top two from each group plus two more.  We need the logic for specifying those two teams.  

We might also want to be prepared to handle only two pools.  Kind of wish we had some idea of how the team registration was progressing.

**Comment by ahundiak** [comment]
There is also one fairly important schema change that needs to be made.  

Currently the pool information is stored in the game element while the pool team stuff is in the team element.  Logical but prevent cross pool play.  And even without U10 power pooling, I suspect we may have cases where we need cross pool play just to give the teams enough games to play.  All depends on team counts and such.

So the pool information will be moved from the game entity to the team entity.  Should only require a bit of refactoring in the calculators so no big deal.  I also want to try and get a better handle of the various pool keys/names/slots so we can avoid some of the string manipulations.

You don't really need to do anything about this right now though feel free to tweak the schema for the tests to have all the pool information be in the team entities.

**Comment by rrone** [comment]
Pushed For Review:
- MedalRoundCalculator
- Test cases for 1, 2, 3, 4 pools, QF, SF, FM
- YAML data files for 1, 2, 3, 4 pools, QF, SF, FM #

**Comment by rrone** [comment]
Duplicated by Issue #136
